import { db } from '@/db';
import { characters } from '@/db/schema';

async function main() {
    const sampleCharacters = [
        // Book 1 Characters
        {
            name: 'Billy Lionheart',
            description: 'A human boy. Mortal. The main character in this series.',
            species: 'Human',
            type: 'Mortal',
            appearsInBooks: [1, 2, 3],
            createdAt: '2024-01-01T12:00:00.000Z',
        },
        {
            name: 'Leonard Lion',
            description: 'A Lion. Billy\'s nanny, guardian and eventually, Papa Lion.',
            species: 'Lion',
            type: 'Animal',
            appearsInBooks: [1, 2, 3],
            createdAt: '2024-01-01T12:00:00.000Z',
        },
        {
            name: 'Ava',
            description: 'A human woman. Leonard\'s counsellor and one of Billy\'s foster parents.',
            species: 'Human',
            type: 'Mortal',
            appearsInBooks: [1],
            createdAt: '2024-01-01T12:00:00.000Z',
        },
        {
            name: 'Boris',
            description: 'A human man. A rescue pilot who found Billy when he was orphaned as a baby. One of Billy\'s foster parents.',
            species: 'Human',
            type: 'Mortal',
            appearsInBooks: [1],
            createdAt: '2024-01-01T12:00:00.000Z',
        },
        {
            name: 'Mei',
            description: 'A human woman. A rescue pilot who found Billy when he was orphaned as a baby. One of Billy\'s foster parents. She is very petite. When Billy was six, she secretly taught him how to fly planes.',
            species: 'Human',
            type: 'Mortal',
            appearsInBooks: [1, 2],
            createdAt: '2024-01-01T12:00:00.000Z',
        },
        {
            name: 'Leo',
            description: 'A human man. Scientist. Inventor. Mei\'s husband and one of Billy\'s foster parents.',
            species: 'Human',
            type: 'Mortal',
            appearsInBooks: [1],
            createdAt: '2024-01-01T12:00:00.000Z',
        },
        {
            name: 'Jayden',
            description: 'An immortal man. When he was a mortal, he was going to marry Ava, but he was killed while saving Ava\'s life. He returned as an immortal king with superpowers.',
            species: 'Human',
            type: 'Immortal',
            appearsInBooks: [1, 2],
            createdAt: '2024-01-01T12:00:00.000Z',
        },
        {
            name: 'Lina',
            description: 'Lioness. Leonard\'s mate, which is animal language for wife. Billy\'s Momma lion.',
            species: 'Lion',
            type: 'Animal',
            appearsInBooks: [1, 3],
            createdAt: '2024-01-01T12:00:00.000Z',
        },
        {
            name: 'Mike',
            description: 'Lion cub who grows into a young lion. Billy\'s lion brother. Mitch\'s twin.',
            species: 'Lion',
            type: 'Animal',
            appearsInBooks: [1],
            createdAt: '2024-01-01T12:00:00.000Z',
        },
        {
            name: 'Mitch',
            description: 'Lion cub who grows into a young lion. Billy\'s lion brother. Mike\'s twin. Owes Cha Cha an unconditional favour.',
            species: 'Lion',
            type: 'Animal',
            appearsInBooks: [1, 3],
            createdAt: '2024-01-01T12:00:00.000Z',
        },
        {
            name: 'Lydia',
            description: 'An immortal woman. Ruler of Lydia\'s Kingdom.',
            species: 'Human',
            type: 'Immortal',
            appearsInBooks: [1],
            createdAt: '2024-01-01T12:00:00.000Z',
        },
        {
            name: 'Ella',
            description: 'An immortal woman. Billy\'s real mother.',
            species: 'Human',
            type: 'Immortal',
            appearsInBooks: [1],
            createdAt: '2024-01-01T12:00:00.000Z',
        },
        {
            name: 'Jake',
            description: 'An immortal man. Billy\'s real father.',
            species: 'Human',
            type: 'Immortal',
            appearsInBooks: [1],
            createdAt: '2024-01-01T12:00:00.000Z',
        },
        {
            name: 'Cha Cha',
            description: 'Monkey. The leader of the monkeys where the lions live. Always up to mischief. He shot Leonard with a gun.',
            species: 'Monkey',
            type: 'Animal',
            appearsInBooks: [1, 2, 3],
            createdAt: '2024-01-01T12:00:00.000Z',
        },
        {
            name: 'Henrieta Hippo',
            description: 'Hippopotamus. Leonard\'s friend.',
            species: 'Hippopotamus',
            type: 'Animal',
            appearsInBooks: [1],
            createdAt: '2024-01-01T12:00:00.000Z',
        },
        // Book 2 Characters
        {
            name: 'Bluma',
            description: 'A human girl. She is Billy\'s toddlerhood friend, and a fellow student in his new school. Smart, stubborn, mischievous girl who learns humility and faith.',
            species: 'Human',
            type: 'Mortal',
            appearsInBooks: [2, 3],
            createdAt: '2024-01-01T12:00:00.000Z',
        },
        {
            name: 'Mathilda',
            description: 'An immortal. During the 7 Year Tribulation, Mathilda helped take care of Billy and Bluma. She helped Bluma\'s mother deliver baby Bluma. She also took care of Billy when he was a toddler. She was killed for her faith in Christ. After the 7 Year Tribulation, she returned, resurrected as an immortal, to reign with the King of Kings.',
            species: 'Human',
            type: 'Immortal',
            appearsInBooks: [2, 3],
            createdAt: '2024-01-01T12:00:00.000Z',
        },
        {
            name: 'Mary',
            description: 'A human woman. Bluma\'s mother.',
            species: 'Human',
            type: 'Mortal',
            appearsInBooks: [2],
            createdAt: '2024-01-01T12:00:00.000Z',
        },
        {
            name: 'Junta',
            description: 'A human young man. Secret cult leader. Villain running a dungeon and hunting island.',
            species: 'Human',
            type: 'Mortal',
            appearsInBooks: [2],
            createdAt: '2024-01-01T12:00:00.000Z',
        },
        {
            name: 'Anne',
            description: 'A human girl. She wears strong perfume which some find offensive. Bluma\'s roommate in campus. All students in St Lydia\'s Academy, live in St Lydia\'s Hearth.',
            species: 'Human',
            type: 'Mortal',
            appearsInBooks: [2, 3],
            createdAt: '2024-01-01T12:00:00.000Z',
        },
        {
            name: 'Professor Abel',
            description: 'A human man. The headmaster of Lydia\'s Academy. Has a grudge against Billy and Bluma because before the semester began, they broke curfew and scaled the school gates by bouncing off his belly like a trampoline. He also lost his toupee to Cha Cha, while chasing the children.',
            species: 'Human',
            type: 'Mortal',
            appearsInBooks: [2, 3],
            createdAt: '2024-01-01T12:00:00.000Z',
        },
        {
            name: 'Bernie',
            description: 'A grizzly bear and proud cave owner.',
            species: 'Bear',
            type: 'Animal',
            appearsInBooks: [2],
            createdAt: '2024-01-01T12:00:00.000Z',
        },
        // Book 3 Characters
        {
            name: 'Miss Steel',
            description: 'A human woman. Billy\'s form teacher.',
            species: 'Human',
            type: 'Mortal',
            appearsInBooks: [3],
            createdAt: '2024-01-01T12:00:00.000Z',
        },
        {
            name: 'Samson',
            description: 'An immortal. School teacher, Gym coach and discipline master in St. Lydia\'s Academy. Looks and acts like a very strong mortal man. Everyone assumes that he is just an ordinary human man.',
            species: 'Human',
            type: 'Immortal',
            appearsInBooks: [3],
            createdAt: '2024-01-01T12:00:00.000Z',
        },
        {
            name: 'Elijah',
            description: 'A human boy. The biggest boy in Billy\'s class.',
            species: 'Human',
            type: 'Mortal',
            appearsInBooks: [3],
            createdAt: '2024-01-01T12:00:00.000Z',
        },
        {
            name: 'Trevor',
            description: 'A human boy. The school bully and one of the bigger boys in St Lydia\'s Academy.',
            species: 'Human',
            type: 'Mortal',
            appearsInBooks: [3],
            createdAt: '2024-01-01T12:00:00.000Z',
        },
        {
            name: 'Joseph',
            description: 'A human boy. Orphaned when his dad stuck his head into Leonard\'s mouth and the lion sneezed. Has a grudge against Leonard. Joseph was taken in by Ethan and raised to be a priest.',
            species: 'Human',
            type: 'Mortal',
            appearsInBooks: [3],
            createdAt: '2024-01-01T12:00:00.000Z',
        },
        {
            name: 'Ethan',
            description: 'An immortal priest. Was martyred during the Tribulation and returned as a resurrected saint. He is one of King Jayden\'s best friends from their time before the Tribulation began.',
            species: 'Human',
            type: 'Immortal',
            appearsInBooks: [3],
            createdAt: '2024-01-01T12:00:00.000Z',
        },
    ];

    await db.insert(characters).values(sampleCharacters);
    
    console.log('✅ Characters seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});