import { db } from '@/db';
import { characters } from '@/db/schema';

async function main() {
    const sampleCharacters = [
        {
            name: 'Leonard Lion',
            species: 'Lion',
            type: 'Animal',
            description: "A Lion. Billy's nanny, guardian and eventually, Papa Lion.",
            appearsInBooks: [1, 2, 3],
            createdAt: '2024-01-01T12:00:00.000Z',
        },
        {
            name: 'Billy Lionheart',
            species: 'Human',
            type: 'Mortal',
            description: 'A human boy. Mortal. The main character in this series.',
            appearsInBooks: [1, 2, 3],
            createdAt: '2024-01-01T12:00:00.000Z',
        },
        {
            name: 'Ava',
            species: 'Human',
            type: 'Mortal',
            description: "A human woman. Leonard's counsellor and one of Billy's foster parents.",
            appearsInBooks: [1, 2, 3],
            createdAt: '2024-01-01T12:00:00.000Z',
        },
        {
            name: 'Boris',
            species: 'Human',
            type: 'Mortal',
            description: "A human man. A rescue pilot who found Billy when he was orphaned as a baby. One of Billy's foster parents.",
            appearsInBooks: [1, 2, 3],
            createdAt: '2024-01-01T12:00:00.000Z',
        },
        {
            name: 'Mei',
            species: 'Human',
            type: 'Mortal',
            description: "A human woman. A rescue pilot who found Billy when he was orphaned as a baby. One of Billy's foster parents.",
            appearsInBooks: [1, 2, 3],
            createdAt: '2024-01-01T12:00:00.000Z',
        },
        {
            name: 'Leo',
            species: 'Human',
            type: 'Mortal',
            description: "A human man. Scientist. Inventor. Mei's husband and one of Billy's foster parents.",
            appearsInBooks: [1, 2, 3],
            createdAt: '2024-01-01T12:00:00.000Z',
        },
        {
            name: 'Jayden',
            species: 'Human',
            type: 'Immortal',
            description: "An immortal man. When he was a mortal, he was going to marry Ava, but he was killed while saving Ava's life. He returned as an immortal king with superpowers.",
            appearsInBooks: [1, 2, 3],
            createdAt: '2024-01-01T12:00:00.000Z',
        },
        {
            name: 'Lina',
            species: 'Lion',
            type: 'Animal',
            description: "Lioness. Leonard's mate, which is animal language for wife. Billy's Momma lion.",
            appearsInBooks: [1, 2, 3],
            createdAt: '2024-01-01T12:00:00.000Z',
        },
        {
            name: 'Mike',
            species: 'Lion',
            type: 'Animal',
            description: "Lion cub who grows into a young lion. Billy's lion brother. Mitch's twin.",
            appearsInBooks: [1, 2, 3],
            createdAt: '2024-01-01T12:00:00.000Z',
        },
        {
            name: 'Mitch',
            species: 'Lion',
            type: 'Animal',
            description: "Lion cub who grows into a young lion. Billy's lion brother. Mike's twin.",
            appearsInBooks: [1, 2, 3],
            createdAt: '2024-01-01T12:00:00.000Z',
        },
        {
            name: 'Lydia',
            species: 'Human',
            type: 'Immortal',
            description: "An immortal woman. Ruler of Lydia's Kingdom.",
            appearsInBooks: [1, 2, 3],
            createdAt: '2024-01-01T12:00:00.000Z',
        },
        {
            name: 'Ella',
            species: 'Human',
            type: 'Immortal',
            description: "An immortal woman. Billy's real mother.",
            appearsInBooks: [1, 2, 3],
            createdAt: '2024-01-01T12:00:00.000Z',
        },
        {
            name: 'Jake',
            species: 'Human',
            type: 'Immortal',
            description: "An immortal man. Billy's real father.",
            appearsInBooks: [1, 2, 3],
            createdAt: '2024-01-01T12:00:00.000Z',
        },
        {
            name: 'Koen',
            species: 'Human',
            type: 'Mortal',
            description: 'A human boy Billy befriends on the way to Celestial City.',
            appearsInBooks: [1, 2, 3],
            createdAt: '2024-01-01T12:00:00.000Z',
        },
        {
            name: 'Waru',
            species: 'Human',
            type: 'Mortal',
            description: "A human man. Koen's father and village chief.",
            appearsInBooks: [1, 2, 3],
            createdAt: '2024-01-01T12:00:00.000Z',
        },
        {
            name: 'Ralph',
            species: 'Human',
            type: 'Mortal',
            description: "A human man. Leonard's business partner.",
            appearsInBooks: [1, 2, 3],
            createdAt: '2024-01-01T12:00:00.000Z',
        },
        {
            name: 'Pete',
            species: 'Lion',
            type: 'Animal',
            description: "A lion cub. One of Leonard & Lina's triplets.",
            appearsInBooks: [1, 2, 3],
            createdAt: '2024-01-01T12:00:00.000Z',
        },
        {
            name: 'Dick',
            species: 'Lion',
            type: 'Animal',
            description: "A lion cub. One of Leonard & Lina's triplets.",
            appearsInBooks: [1, 2, 3],
            createdAt: '2024-01-01T12:00:00.000Z',
        },
        {
            name: 'Kit',
            species: 'Lion',
            type: 'Animal',
            description: "A lion cub. One of Leonard & Lina's triplets.",
            appearsInBooks: [1, 2, 3],
            createdAt: '2024-01-01T12:00:00.000Z',
        },
        {
            name: 'Tike',
            species: 'Lion',
            type: 'Animal',
            description: "A lion cub. Grown up Mike's son.",
            appearsInBooks: [1, 2, 3],
            createdAt: '2024-01-01T12:00:00.000Z',
        },
        {
            name: 'Tina',
            species: 'Lion',
            type: 'Animal',
            description: "A lion cub. Grown up Mitch's daughter.",
            appearsInBooks: [1, 2, 3],
            createdAt: '2024-01-01T12:00:00.000Z',
        },
        {
            name: 'Sylvia',
            species: 'Lion',
            type: 'Animal',
            description: "A lion cub. Grown up Mitch's daughter.",
            appearsInBooks: [1, 2, 3],
            createdAt: '2024-01-01T12:00:00.000Z',
        },
        {
            name: 'Cha Cha',
            species: 'Monkey',
            type: 'Animal',
            description: 'Monkey. The leader of the monkeys where the lions live.',
            appearsInBooks: [1, 2, 3],
            createdAt: '2024-01-01T12:00:00.000Z',
        },
        {
            name: 'Henrieta Hippo',
            species: 'Hippopotamus',
            type: 'Animal',
            description: "Hippopotamus. Leonard's friend.",
            appearsInBooks: [1, 2, 3],
            createdAt: '2024-01-01T12:00:00.000Z',
        },
        {
            name: 'Bluma',
            species: 'Human',
            type: 'Mortal',
            description: "A human girl. She is Billy's toddlerhood friend, and a fellow student in his new school.",
            appearsInBooks: [2, 3],
            createdAt: '2024-01-01T12:00:00.000Z',
        },
        {
            name: 'Mathilda',
            species: 'Human',
            type: 'Immortal',
            description: 'An immortal. During the 7 Year Tribulation, Mathilda helped take care of Billy and Bluma. She helped Bluma\'s mother deliver baby Bluma. She was killed for her faith in Christ and returned as a resurrected immortal.',
            appearsInBooks: [2, 3],
            createdAt: '2024-01-01T12:00:00.000Z',
        },
        {
            name: 'Mary',
            species: 'Human',
            type: 'Mortal',
            description: "A human woman. Bluma's mother.",
            appearsInBooks: [2, 3],
            createdAt: '2024-01-01T12:00:00.000Z',
        },
        {
            name: 'Beast',
            species: 'Human',
            type: 'Immortal',
            description: 'The Antichrist who reigned during the 7 year Tribulation and murdered many for their faith in Jesus. He was thrown into the Lake of Fire.',
            appearsInBooks: [2, 3],
            createdAt: '2024-01-01T12:00:00.000Z',
        },
        {
            name: 'Stephanie',
            species: 'Human',
            type: 'Mortal',
            description: "A human woman. Works at Billy's Secret Recipe as Leonard's secretary.",
            appearsInBooks: [2, 3],
            createdAt: '2024-01-01T12:00:00.000Z',
        },
        {
            name: 'Anne',
            species: 'Human',
            type: 'Mortal',
            description: "A human girl. She wears strong perfume which some find offensive. Bluma's roommate in campus.",
            appearsInBooks: [2, 3],
            createdAt: '2024-01-01T12:00:00.000Z',
        },
        {
            name: 'Professor Abel',
            species: 'Human',
            type: 'Mortal',
            description: "A human man. The headmaster of Lydia's Academy.",
            appearsInBooks: [2, 3],
            createdAt: '2024-01-01T12:00:00.000Z',
        },
        {
            name: 'Bernie',
            species: 'Bear',
            type: 'Animal',
            description: 'A grizzly bear and proud cave owner.',
            appearsInBooks: [2, 3],
            createdAt: '2024-01-01T12:00:00.000Z',
        },
        {
            name: 'Dorothy',
            species: 'Sparrow',
            type: 'Animal',
            description: 'A sparrow. She likes pretty blue flowers.',
            appearsInBooks: [2, 3],
            createdAt: '2024-01-01T12:00:00.000Z',
        },
        {
            name: 'Junta',
            species: 'Human',
            type: 'Mortal',
            description: 'A human young man. Secret cult leader.',
            appearsInBooks: [2, 3],
            createdAt: '2024-01-01T12:00:00.000Z',
        },
        {
            name: 'Spencer',
            species: 'Human',
            type: 'Mortal',
            description: 'A human boy. Goes by Spence. A fellow kid prisoner of Junta.',
            appearsInBooks: [2, 3],
            createdAt: '2024-01-01T12:00:00.000Z',
        },
        {
            name: 'Mia',
            species: 'Human',
            type: 'Mortal',
            description: "A human girl. Spencer's sister and fellow prisoner.",
            appearsInBooks: [2, 3],
            createdAt: '2024-01-01T12:00:00.000Z',
        },
        {
            name: 'Jose',
            species: 'Human',
            type: 'Mortal',
            description: 'A human boy. A fellow child prisoner of Junta who tried to escape but got caught.',
            appearsInBooks: [2, 3],
            createdAt: '2024-01-01T12:00:00.000Z',
        },
        {
            name: 'Owen',
            species: 'Human',
            type: 'Mortal',
            description: 'A human man. Former hunting buddy of Junta who refused to join his schemes and was imprisoned. Wears an eye patch.',
            appearsInBooks: [2, 3],
            createdAt: '2024-01-01T12:00:00.000Z',
        },
        {
            name: 'Miss Steel',
            species: 'Human',
            type: 'Mortal',
            description: "A human woman. Billy's form teacher.",
            appearsInBooks: [3],
            createdAt: '2024-01-01T12:00:00.000Z',
        },
        {
            name: 'Samson',
            species: 'Human',
            type: 'Immortal',
            description: "An immortal. School teacher, Gym coach and discipline master in St. Lydia's Academy.",
            appearsInBooks: [3],
            createdAt: '2024-01-01T12:00:00.000Z',
        },
        {
            name: 'Elijah',
            species: 'Human',
            type: 'Mortal',
            description: "A human boy. The biggest boy in Billy's class.",
            appearsInBooks: [3],
            createdAt: '2024-01-01T12:00:00.000Z',
        },
        {
            name: 'Trevor',
            species: 'Human',
            type: 'Mortal',
            description: "A human boy. The school bully and one of the bigger boys in St Lydia's Academy.",
            appearsInBooks: [3],
            createdAt: '2024-01-01T12:00:00.000Z',
        },
        {
            name: 'Joseph',
            species: 'Human',
            type: 'Mortal',
            description: "A human boy. Orphaned when his dad stuck his head into Leonard's mouth and the lion sneezed. Has a grudge against Leonard.",
            appearsInBooks: [3],
            createdAt: '2024-01-01T12:00:00.000Z',
        },
        {
            name: 'Ethan',
            species: 'Human',
            type: 'Immortal',
            description: 'An immortal priest. Was martyred during the Tribulation and returned as a resurrected saint.',
            appearsInBooks: [3],
            createdAt: '2024-01-01T12:00:00.000Z',
        },
        {
            name: 'Teacher Mabel',
            species: 'Human',
            type: 'Mortal',
            description: "A human woman. A teacher in St Lydia's Academy.",
            appearsInBooks: [3],
            createdAt: '2024-01-01T12:00:00.000Z',
        },
        {
            name: 'Toby',
            species: 'Dog',
            type: 'Animal',
            description: "A dog. Mia's pet golden retriever who views himself as her personal bodyguard.",
            appearsInBooks: [3],
            createdAt: '2024-01-01T12:00:00.000Z',
        },
    ];

    await db.insert(characters).values(sampleCharacters);
    
    console.log('✅ Characters seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});